# Program name
PROG	= tput

# Default stack size and optimization (can be overridden by cmd line)
#   These values have been tested and certified as working
STACK		*= 512
OPTIMIZE	*= 79
LDLIBS  = -l/usr/lib/libtermcap.204
  
# Delivery directory
BINDIR	= /usr/bin
HAS_BSD_MANPAGE = true

.INCLUDE : /src/gno/prog.mk
