#
# This makefile is intended for use with dmake(1) on Apple IIGS
#

# Program name
PROG = asa
OPTIMIZE = 79
STACK = 512 

# Delivery directory
BINDIR = /usr/bin
HAS_BSD_MANPAGE = true

.INCLUDE:	/src/gno/prog.mk
